// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentService.proto

package cn.iamding.drpc.client.rpc.student;

public interface SubmitResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SubmitResult)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string server = 2;</code>
   */
  java.lang.String getServer();

  /**
   * <code>string server = 2;</code>
   */
  com.google.protobuf.ByteString
  getServerBytes();

  /**
   * <code>.Student data = 3;</code>
   */
  boolean hasData();

  /**
   * <code>.Student data = 3;</code>
   */
  cn.iamding.drpc.client.rpc.student.Student getData();

  /**
   * <code>.Student data = 3;</code>
   */
  cn.iamding.drpc.client.rpc.student.StudentOrBuilder getDataOrBuilder();
}
