// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentService.proto

package cn.iamding.drpc.client.rpc.student;

/**
 * Protobuf type {@code SubmitResult}
 */
public final class SubmitResult extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:SubmitResult)
        SubmitResultOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use SubmitResult.newBuilder() to construct.
  private SubmitResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private SubmitResult() {
    code_ = 0;
    server_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private SubmitResult(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            server_ = s;
            break;
          }
          case 26: {
            cn.iamding.drpc.client.rpc.student.Student.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(cn.iamding.drpc.client.rpc.student.Student.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return cn.iamding.drpc.client.rpc.student.StudentProto.internal_static_SubmitResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return cn.iamding.drpc.client.rpc.student.StudentProto.internal_static_SubmitResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    cn.iamding.drpc.client.rpc.student.SubmitResult.class, cn.iamding.drpc.client.rpc.student.SubmitResult.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;

  /**
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int SERVER_FIELD_NUMBER = 2;
  private volatile java.lang.Object server_;

  /**
   * <code>string server = 2;</code>
   */
  public java.lang.String getServer() {
    java.lang.Object ref = server_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      server_ = s;
      return s;
    }
  }

  /**
   * <code>string server = 2;</code>
   */
  public com.google.protobuf.ByteString
  getServerBytes() {
    java.lang.Object ref = server_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      server_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private cn.iamding.drpc.client.rpc.student.Student data_;

  /**
   * <code>.Student data = 3;</code>
   */
  public boolean hasData() {
    return data_ != null;
  }

  /**
   * <code>.Student data = 3;</code>
   */
  public cn.iamding.drpc.client.rpc.student.Student getData() {
    return data_ == null ? cn.iamding.drpc.client.rpc.student.Student.getDefaultInstance() : data_;
  }

  /**
   * <code>.Student data = 3;</code>
   */
  public cn.iamding.drpc.client.rpc.student.StudentOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getServerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, server_);
    }
    if (data_ != null) {
      output.writeMessage(3, getData());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, code_);
    }
    if (!getServerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, server_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(3, getData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof cn.iamding.drpc.client.rpc.student.SubmitResult)) {
      return super.equals(obj);
    }
    cn.iamding.drpc.client.rpc.student.SubmitResult other = (cn.iamding.drpc.client.rpc.student.SubmitResult) obj;

    boolean result = true;
    result = result && (getCode()
            == other.getCode());
    result = result && getServer()
            .equals(other.getServer());
    result = result && (hasData() == other.hasData());
    if (hasData()) {
      result = result && getData()
              .equals(other.getData());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + SERVER_FIELD_NUMBER;
    hash = (53 * hash) + getServer().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(cn.iamding.drpc.client.rpc.student.SubmitResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code SubmitResult}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SubmitResult)
          cn.iamding.drpc.client.rpc.student.SubmitResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return cn.iamding.drpc.client.rpc.student.StudentProto.internal_static_SubmitResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.iamding.drpc.client.rpc.student.StudentProto.internal_static_SubmitResult_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      cn.iamding.drpc.client.rpc.student.SubmitResult.class, cn.iamding.drpc.client.rpc.student.SubmitResult.Builder.class);
    }

    // Construct using cn.iamding.drpc.client.rpc.student.SubmitResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    public Builder clear() {
      super.clear();
      code_ = 0;

      server_ = "";

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return cn.iamding.drpc.client.rpc.student.StudentProto.internal_static_SubmitResult_descriptor;
    }

    public cn.iamding.drpc.client.rpc.student.SubmitResult getDefaultInstanceForType() {
      return cn.iamding.drpc.client.rpc.student.SubmitResult.getDefaultInstance();
    }

    public cn.iamding.drpc.client.rpc.student.SubmitResult build() {
      cn.iamding.drpc.client.rpc.student.SubmitResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.iamding.drpc.client.rpc.student.SubmitResult buildPartial() {
      cn.iamding.drpc.client.rpc.student.SubmitResult result = new cn.iamding.drpc.client.rpc.student.SubmitResult(this);
      result.code_ = code_;
      result.server_ = server_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.iamding.drpc.client.rpc.student.SubmitResult) {
        return mergeFrom((cn.iamding.drpc.client.rpc.student.SubmitResult) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.iamding.drpc.client.rpc.student.SubmitResult other) {
      if (other == cn.iamding.drpc.client.rpc.student.SubmitResult.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getServer().isEmpty()) {
        server_ = other.server_;
        onChanged();
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      cn.iamding.drpc.client.rpc.student.SubmitResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.iamding.drpc.client.rpc.student.SubmitResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int code_;

    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    /**
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {

      code_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {

      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object server_ = "";

    /**
     * <code>string server = 2;</code>
     */
    public java.lang.String getServer() {
      java.lang.Object ref = server_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        server_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string server = 2;</code>
     */
    public com.google.protobuf.ByteString
    getServerBytes() {
      java.lang.Object ref = server_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string server = 2;</code>
     */
    public Builder setServer(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      server_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string server = 2;</code>
     */
    public Builder clearServer() {

      server_ = getDefaultInstance().getServer();
      onChanged();
      return this;
    }

    /**
     * <code>string server = 2;</code>
     */
    public Builder setServerBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      server_ = value;
      onChanged();
      return this;
    }

    private cn.iamding.drpc.client.rpc.student.Student data_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            cn.iamding.drpc.client.rpc.student.Student, cn.iamding.drpc.client.rpc.student.Student.Builder, cn.iamding.drpc.client.rpc.student.StudentOrBuilder> dataBuilder_;

    /**
     * <code>.Student data = 3;</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }

    /**
     * <code>.Student data = 3;</code>
     */
    public cn.iamding.drpc.client.rpc.student.Student getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? cn.iamding.drpc.client.rpc.student.Student.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }

    /**
     * <code>.Student data = 3;</code>
     */
    public Builder setData(cn.iamding.drpc.client.rpc.student.Student value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.Student data = 3;</code>
     */
    public Builder setData(
            cn.iamding.drpc.client.rpc.student.Student.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.Student data = 3;</code>
     */
    public Builder mergeData(cn.iamding.drpc.client.rpc.student.Student value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
                  cn.iamding.drpc.client.rpc.student.Student.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.Student data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.Student data = 3;</code>
     */
    public cn.iamding.drpc.client.rpc.student.Student.Builder getDataBuilder() {

      onChanged();
      return getDataFieldBuilder().getBuilder();
    }

    /**
     * <code>.Student data = 3;</code>
     */
    public cn.iamding.drpc.client.rpc.student.StudentOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
                cn.iamding.drpc.client.rpc.student.Student.getDefaultInstance() : data_;
      }
    }

    /**
     * <code>.Student data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            cn.iamding.drpc.client.rpc.student.Student, cn.iamding.drpc.client.rpc.student.Student.Builder, cn.iamding.drpc.client.rpc.student.StudentOrBuilder>
    getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                cn.iamding.drpc.client.rpc.student.Student, cn.iamding.drpc.client.rpc.student.Student.Builder, cn.iamding.drpc.client.rpc.student.StudentOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SubmitResult)
  }

  // @@protoc_insertion_point(class_scope:SubmitResult)
  private static final cn.iamding.drpc.client.rpc.student.SubmitResult DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new cn.iamding.drpc.client.rpc.student.SubmitResult();
  }

  public static cn.iamding.drpc.client.rpc.student.SubmitResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubmitResult>
          PARSER = new com.google.protobuf.AbstractParser<SubmitResult>() {
    public SubmitResult parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubmitResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubmitResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubmitResult> getParserForType() {
    return PARSER;
  }

  public cn.iamding.drpc.client.rpc.student.SubmitResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

