// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentService.proto

package cn.iamding.drpc.server.rpc.student;

public interface SubmitResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubmitResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

    /**
     * <code>string server = 2;</code>
   */
    String getServer();
  /**
   * <code>string server = 2;</code>
   */
  com.google.protobuf.ByteString
  getServerBytes();

  /**
   * <code>.Student data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.Student data = 3;</code>
   */
  Student getData();
  /**
   * <code>.Student data = 3;</code>
   */
  StudentOrBuilder getDataOrBuilder();
}
