// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CloudDisk.proto

package cn.iamding.drpc.client.rpc.disk;

public final class CloudDiskProto {
    private CloudDiskProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RPCUploadFileResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_RPCUploadFileResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RPCUploadFileResponse_UploadResult_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_RPCUploadFileResponse_UploadResult_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RPCUploadFileRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_RPCUploadFileRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\017CloudDisk.proto\"\265\001\n\025RPCUploadFileRespo" +
                        "nse\0221\n\004data\030\001 \001(\0132#.RPCUploadFileRespons" +
                        "e.UploadResult\022\014\n\004code\030\002 \001(\t\022\013\n\003msg\030\003 \001(" +
                        "\t\022\032\n\022UploadJsonResponse\030\006 \001(\t\0322\n\014UploadR" +
                        "esult\022\021\n\tshare_url\030\004 \001(\t\022\017\n\007file_id\030\005 \001(" +
                        "\t\"L\n\024RPCUploadFileRequest\022\017\n\007content\030\001 \001" +
                        "(\014\022\020\n\010fileType\030\002 \001(\t\022\021\n\tshareType\030\003 \001(\t2" +
                        "P\n\020CloudDiskService\022<\n\trpcUpload\022\025.RPCUp" +
                        "loadFileRequest\032\026.RPCUploadFileResponse\"" +
                        "\000BA\n!com.iqiyi.hotchat.cloud.disk.grpcB\016",
                "CloudDiskProtoP\001\242\002\tCloudDiskb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_RPCUploadFileResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_RPCUploadFileResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_RPCUploadFileResponse_descriptor,
                new String[]{"Data", "Code", "Msg", "UploadJsonResponse",});
        internal_static_RPCUploadFileResponse_UploadResult_descriptor =
                internal_static_RPCUploadFileResponse_descriptor.getNestedTypes().get(0);
        internal_static_RPCUploadFileResponse_UploadResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_RPCUploadFileResponse_UploadResult_descriptor,
                new String[]{"ShareUrl", "FileId",});
        internal_static_RPCUploadFileRequest_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_RPCUploadFileRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_RPCUploadFileRequest_descriptor,
                new String[]{"Content", "FileType", "ShareType",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
