// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentService.proto

package cn.iamding.drpc.client.rpc.student;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 2;</code>
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 2;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>string photo = 4;</code>
   */
  java.lang.String getPhoto();
  /**
   * <code>string photo = 4;</code>
   */
  com.google.protobuf.ByteString
      getPhotoBytes();
}
