// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentService.proto

package cn.iamding.drpc.client.rpc.student;

public interface SubmitResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubmitResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.Student data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.Student data = 3;</code>
   */
  cn.iamding.drpc.client.rpc.student.Student getData();
  /**
   * <code>.Student data = 3;</code>
   */
  cn.iamding.drpc.client.rpc.student.StudentOrBuilder getDataOrBuilder();
}
