// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CloudDisk.proto

package cn.iamding.drpc.server.rpc.disk;

/**
 * Protobuf type {@code RPCUploadFileResponse}
 */
public final class RPCUploadFileResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:RPCUploadFileResponse)
        RPCUploadFileResponseOrBuilder {
    // Use RPCUploadFileResponse.newBuilder() to construct.
    private RPCUploadFileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private RPCUploadFileResponse() {
        code_ = "";
        msg_ = "";
        uploadJsonResponse_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private RPCUploadFileResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        RPCUploadFileResponse.UploadResult.Builder subBuilder = null;
                        if (data_ != null) {
                            subBuilder = data_.toBuilder();
                        }
                        data_ = input.readMessage(RPCUploadFileResponse.UploadResult.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(data_);
                            data_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        code_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        msg_ = s;
                        break;
                    }
                    case 50: {
                        String s = input.readStringRequireUtf8();

                        uploadJsonResponse_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return CloudDiskProto.internal_static_RPCUploadFileResponse_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return CloudDiskProto.internal_static_RPCUploadFileResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        RPCUploadFileResponse.class, RPCUploadFileResponse.Builder.class);
    }

    public interface UploadResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RPCUploadFileResponse.UploadResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string share_url = 4;</code>
         */
        String getShareUrl();

        /**
         * <code>string share_url = 4;</code>
         */
        com.google.protobuf.ByteString
        getShareUrlBytes();

        /**
         * <code>string file_id = 5;</code>
         */
        String getFileId();

        /**
         * <code>string file_id = 5;</code>
         */
        com.google.protobuf.ByteString
        getFileIdBytes();
    }

    /**
     * Protobuf type {@code RPCUploadFileResponse.UploadResult}
     */
    public static final class UploadResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:RPCUploadFileResponse.UploadResult)
            UploadResultOrBuilder {
        // Use UploadResult.newBuilder() to construct.
        private UploadResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private UploadResult() {
            shareUrl_ = "";
            fileId_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private UploadResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            shareUrl_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            fileId_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return CloudDiskProto.internal_static_RPCUploadFileResponse_UploadResult_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return CloudDiskProto.internal_static_RPCUploadFileResponse_UploadResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            RPCUploadFileResponse.UploadResult.class, RPCUploadFileResponse.UploadResult.Builder.class);
        }

        public static final int SHARE_URL_FIELD_NUMBER = 4;
        private volatile Object shareUrl_;

        /**
         * <code>string share_url = 4;</code>
         */
        public String getShareUrl() {
            Object ref = shareUrl_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                shareUrl_ = s;
                return s;
            }
        }

        /**
         * <code>string share_url = 4;</code>
         */
        public com.google.protobuf.ByteString
        getShareUrlBytes() {
            Object ref = shareUrl_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                shareUrl_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FILE_ID_FIELD_NUMBER = 5;
        private volatile Object fileId_;

        /**
         * <code>string file_id = 5;</code>
         */
        public String getFileId() {
            Object ref = fileId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                fileId_ = s;
                return s;
            }
        }

        /**
         * <code>string file_id = 5;</code>
         */
        public com.google.protobuf.ByteString
        getFileIdBytes() {
            Object ref = fileId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                fileId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getShareUrlBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, shareUrl_);
            }
            if (!getFileIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileId_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getShareUrlBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, shareUrl_);
            }
            if (!getFileIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileId_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof RPCUploadFileResponse.UploadResult)) {
                return super.equals(obj);
            }
            RPCUploadFileResponse.UploadResult other = (RPCUploadFileResponse.UploadResult) obj;

            boolean result = true;
            result = result && getShareUrl()
                    .equals(other.getShareUrl());
            result = result && getFileId()
                    .equals(other.getFileId());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SHARE_URL_FIELD_NUMBER;
            hash = (53 * hash) + getShareUrl().hashCode();
            hash = (37 * hash) + FILE_ID_FIELD_NUMBER;
            hash = (53 * hash) + getFileId().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static RPCUploadFileResponse.UploadResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static RPCUploadFileResponse.UploadResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static RPCUploadFileResponse.UploadResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(RPCUploadFileResponse.UploadResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code RPCUploadFileResponse.UploadResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RPCUploadFileResponse.UploadResult)
                RPCUploadFileResponse.UploadResultOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return CloudDiskProto.internal_static_RPCUploadFileResponse_UploadResult_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return CloudDiskProto.internal_static_RPCUploadFileResponse_UploadResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                RPCUploadFileResponse.UploadResult.class, RPCUploadFileResponse.UploadResult.Builder.class);
            }

            // Construct using com.iqiyi.hotchat.cloud.RPCUploadFileResponse.UploadResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                shareUrl_ = "";

                fileId_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return CloudDiskProto.internal_static_RPCUploadFileResponse_UploadResult_descriptor;
            }

            public RPCUploadFileResponse.UploadResult getDefaultInstanceForType() {
                return RPCUploadFileResponse.UploadResult.getDefaultInstance();
            }

            public RPCUploadFileResponse.UploadResult build() {
                RPCUploadFileResponse.UploadResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public RPCUploadFileResponse.UploadResult buildPartial() {
                RPCUploadFileResponse.UploadResult result = new RPCUploadFileResponse.UploadResult(this);
                result.shareUrl_ = shareUrl_;
                result.fileId_ = fileId_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof RPCUploadFileResponse.UploadResult) {
                    return mergeFrom((RPCUploadFileResponse.UploadResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(RPCUploadFileResponse.UploadResult other) {
                if (other == RPCUploadFileResponse.UploadResult.getDefaultInstance()) return this;
                if (!other.getShareUrl().isEmpty()) {
                    shareUrl_ = other.shareUrl_;
                    onChanged();
                }
                if (!other.getFileId().isEmpty()) {
                    fileId_ = other.fileId_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                RPCUploadFileResponse.UploadResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (RPCUploadFileResponse.UploadResult) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object shareUrl_ = "";

            /**
             * <code>string share_url = 4;</code>
             */
            public String getShareUrl() {
                Object ref = shareUrl_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    shareUrl_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string share_url = 4;</code>
             */
            public com.google.protobuf.ByteString
            getShareUrlBytes() {
                Object ref = shareUrl_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    shareUrl_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string share_url = 4;</code>
             */
            public Builder setShareUrl(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                shareUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string share_url = 4;</code>
             */
            public Builder clearShareUrl() {

                shareUrl_ = getDefaultInstance().getShareUrl();
                onChanged();
                return this;
            }

            /**
             * <code>string share_url = 4;</code>
             */
            public Builder setShareUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                shareUrl_ = value;
                onChanged();
                return this;
            }

            private Object fileId_ = "";

            /**
             * <code>string file_id = 5;</code>
             */
            public String getFileId() {
                Object ref = fileId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    fileId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string file_id = 5;</code>
             */
            public com.google.protobuf.ByteString
            getFileIdBytes() {
                Object ref = fileId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    fileId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string file_id = 5;</code>
             */
            public Builder setFileId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                fileId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string file_id = 5;</code>
             */
            public Builder clearFileId() {

                fileId_ = getDefaultInstance().getFileId();
                onChanged();
                return this;
            }

            /**
             * <code>string file_id = 5;</code>
             */
            public Builder setFileIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                fileId_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:RPCUploadFileResponse.UploadResult)
        }

        // @@protoc_insertion_point(class_scope:RPCUploadFileResponse.UploadResult)
        private static final RPCUploadFileResponse.UploadResult DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new RPCUploadFileResponse.UploadResult();
        }

        public static RPCUploadFileResponse.UploadResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<UploadResult>
                PARSER = new com.google.protobuf.AbstractParser<UploadResult>() {
            public UploadResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UploadResult(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<UploadResult> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<UploadResult> getParserForType() {
            return PARSER;
        }

        public RPCUploadFileResponse.UploadResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public static final int DATA_FIELD_NUMBER = 1;
    private RPCUploadFileResponse.UploadResult data_;

    /**
     * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
     */
    public boolean hasData() {
        return data_ != null;
    }

    /**
     * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
     */
    public RPCUploadFileResponse.UploadResult getData() {
        return data_ == null ? RPCUploadFileResponse.UploadResult.getDefaultInstance() : data_;
    }

    /**
     * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
     */
    public RPCUploadFileResponse.UploadResultOrBuilder getDataOrBuilder() {
        return getData();
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile Object code_;

    /**
     * <code>string code = 2;</code>
     */
    public String getCode() {
        Object ref = code_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            code_ = s;
            return s;
        }
    }

    /**
     * <code>string code = 2;</code>
     */
    public com.google.protobuf.ByteString
    getCodeBytes() {
        Object ref = code_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            code_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile Object msg_;

    /**
     * <code>string msg = 3;</code>
     */
    public String getMsg() {
        Object ref = msg_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            msg_ = s;
            return s;
        }
    }

    /**
     * <code>string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
    getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            msg_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int UPLOADJSONRESPONSE_FIELD_NUMBER = 6;
    private volatile Object uploadJsonResponse_;

    /**
     * <code>string UploadJsonResponse = 6;</code>
     */
    public String getUploadJsonResponse() {
        Object ref = uploadJsonResponse_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            uploadJsonResponse_ = s;
            return s;
        }
    }

    /**
     * <code>string UploadJsonResponse = 6;</code>
     */
    public com.google.protobuf.ByteString
    getUploadJsonResponseBytes() {
        Object ref = uploadJsonResponse_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            uploadJsonResponse_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (data_ != null) {
            output.writeMessage(1, getData());
        }
        if (!getCodeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
        }
        if (!getUploadJsonResponseBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, uploadJsonResponse_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (data_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getData());
        }
        if (!getCodeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
        }
        if (!getUploadJsonResponseBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, uploadJsonResponse_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof RPCUploadFileResponse)) {
            return super.equals(obj);
        }
        RPCUploadFileResponse other = (RPCUploadFileResponse) obj;

        boolean result = true;
        result = result && (hasData() == other.hasData());
        if (hasData()) {
            result = result && getData()
                    .equals(other.getData());
        }
        result = result && getCode()
                .equals(other.getCode());
        result = result && getMsg()
                .equals(other.getMsg());
        result = result && getUploadJsonResponse()
                .equals(other.getUploadJsonResponse());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasData()) {
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
        }
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        hash = (37 * hash) + UPLOADJSONRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUploadJsonResponse().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static RPCUploadFileResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static RPCUploadFileResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RPCUploadFileResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static RPCUploadFileResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RPCUploadFileResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static RPCUploadFileResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RPCUploadFileResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static RPCUploadFileResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static RPCUploadFileResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static RPCUploadFileResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static RPCUploadFileResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static RPCUploadFileResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(RPCUploadFileResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code RPCUploadFileResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:RPCUploadFileResponse)
            RPCUploadFileResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return CloudDiskProto.internal_static_RPCUploadFileResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return CloudDiskProto.internal_static_RPCUploadFileResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            RPCUploadFileResponse.class, RPCUploadFileResponse.Builder.class);
        }

        // Construct using com.iqiyi.hotchat.cloud.RPCUploadFileResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            if (dataBuilder_ == null) {
                data_ = null;
            } else {
                data_ = null;
                dataBuilder_ = null;
            }
            code_ = "";

            msg_ = "";

            uploadJsonResponse_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return CloudDiskProto.internal_static_RPCUploadFileResponse_descriptor;
        }

        public RPCUploadFileResponse getDefaultInstanceForType() {
            return RPCUploadFileResponse.getDefaultInstance();
        }

        public RPCUploadFileResponse build() {
            RPCUploadFileResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public RPCUploadFileResponse buildPartial() {
            RPCUploadFileResponse result = new RPCUploadFileResponse(this);
            if (dataBuilder_ == null) {
                result.data_ = data_;
            } else {
                result.data_ = dataBuilder_.build();
            }
            result.code_ = code_;
            result.msg_ = msg_;
            result.uploadJsonResponse_ = uploadJsonResponse_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof RPCUploadFileResponse) {
                return mergeFrom((RPCUploadFileResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(RPCUploadFileResponse other) {
            if (other == RPCUploadFileResponse.getDefaultInstance()) return this;
            if (other.hasData()) {
                mergeData(other.getData());
            }
            if (!other.getCode().isEmpty()) {
                code_ = other.code_;
                onChanged();
            }
            if (!other.getMsg().isEmpty()) {
                msg_ = other.msg_;
                onChanged();
            }
            if (!other.getUploadJsonResponse().isEmpty()) {
                uploadJsonResponse_ = other.uploadJsonResponse_;
                onChanged();
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            RPCUploadFileResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (RPCUploadFileResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private RPCUploadFileResponse.UploadResult data_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                UploadResult, UploadResult.Builder, UploadResultOrBuilder> dataBuilder_;

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public boolean hasData() {
            return dataBuilder_ != null || data_ != null;
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public RPCUploadFileResponse.UploadResult getData() {
            if (dataBuilder_ == null) {
                return data_ == null ? RPCUploadFileResponse.UploadResult.getDefaultInstance() : data_;
            } else {
                return dataBuilder_.getMessage();
            }
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public Builder setData(RPCUploadFileResponse.UploadResult value) {
            if (dataBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                data_ = value;
                onChanged();
            } else {
                dataBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public Builder setData(
                RPCUploadFileResponse.UploadResult.Builder builderForValue) {
            if (dataBuilder_ == null) {
                data_ = builderForValue.build();
                onChanged();
            } else {
                dataBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public Builder mergeData(RPCUploadFileResponse.UploadResult value) {
            if (dataBuilder_ == null) {
                if (data_ != null) {
                    data_ =
                            RPCUploadFileResponse.UploadResult.newBuilder(data_).mergeFrom(value).buildPartial();
                } else {
                    data_ = value;
                }
                onChanged();
            } else {
                dataBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public Builder clearData() {
            if (dataBuilder_ == null) {
                data_ = null;
                onChanged();
            } else {
                data_ = null;
                dataBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public RPCUploadFileResponse.UploadResult.Builder getDataBuilder() {

            onChanged();
            return getDataFieldBuilder().getBuilder();
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        public RPCUploadFileResponse.UploadResultOrBuilder getDataOrBuilder() {
            if (dataBuilder_ != null) {
                return dataBuilder_.getMessageOrBuilder();
            } else {
                return data_ == null ?
                        RPCUploadFileResponse.UploadResult.getDefaultInstance() : data_;
            }
        }

        /**
         * <code>.RPCUploadFileResponse.UploadResult data = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UploadResult, UploadResult.Builder, UploadResultOrBuilder>
        getDataFieldBuilder() {
            if (dataBuilder_ == null) {
                dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UploadResult, UploadResult.Builder, UploadResultOrBuilder>(
                        getData(),
                        getParentForChildren(),
                        isClean());
                data_ = null;
            }
            return dataBuilder_;
        }

        private Object code_ = "";

        /**
         * <code>string code = 2;</code>
         */
        public String getCode() {
            Object ref = code_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                code_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string code = 2;</code>
         */
        public com.google.protobuf.ByteString
        getCodeBytes() {
            Object ref = code_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                code_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string code = 2;</code>
         */
        public Builder setCode(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            code_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string code = 2;</code>
         */
        public Builder clearCode() {

            code_ = getDefaultInstance().getCode();
            onChanged();
            return this;
        }

        /**
         * <code>string code = 2;</code>
         */
        public Builder setCodeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            code_ = value;
            onChanged();
            return this;
        }

        private Object msg_ = "";

        /**
         * <code>string msg = 3;</code>
         */
        public String getMsg() {
            Object ref = msg_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string msg = 3;</code>
         */
        public com.google.protobuf.ByteString
        getMsgBytes() {
            Object ref = msg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string msg = 3;</code>
         */
        public Builder setMsg(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msg_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string msg = 3;</code>
         */
        public Builder clearMsg() {

            msg_ = getDefaultInstance().getMsg();
            onChanged();
            return this;
        }

        /**
         * <code>string msg = 3;</code>
         */
        public Builder setMsgBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            msg_ = value;
            onChanged();
            return this;
        }

        private Object uploadJsonResponse_ = "";

        /**
         * <code>string UploadJsonResponse = 6;</code>
         */
        public String getUploadJsonResponse() {
            Object ref = uploadJsonResponse_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                uploadJsonResponse_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string UploadJsonResponse = 6;</code>
         */
        public com.google.protobuf.ByteString
        getUploadJsonResponseBytes() {
            Object ref = uploadJsonResponse_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                uploadJsonResponse_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string UploadJsonResponse = 6;</code>
         */
        public Builder setUploadJsonResponse(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            uploadJsonResponse_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string UploadJsonResponse = 6;</code>
         */
        public Builder clearUploadJsonResponse() {

            uploadJsonResponse_ = getDefaultInstance().getUploadJsonResponse();
            onChanged();
            return this;
        }

        /**
         * <code>string UploadJsonResponse = 6;</code>
         */
        public Builder setUploadJsonResponseBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            uploadJsonResponse_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:RPCUploadFileResponse)
    }

    // @@protoc_insertion_point(class_scope:RPCUploadFileResponse)
    private static final RPCUploadFileResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new RPCUploadFileResponse();
    }

    public static RPCUploadFileResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RPCUploadFileResponse>
            PARSER = new com.google.protobuf.AbstractParser<RPCUploadFileResponse>() {
        public RPCUploadFileResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new RPCUploadFileResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<RPCUploadFileResponse> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RPCUploadFileResponse> getParserForType() {
        return PARSER;
    }

    public RPCUploadFileResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

